import { PhotosModel } from './photosDataModels';
/**
 * ფოტოს მონაცემები, რომელიც შექმნილია PhotosModel-ის საფუძველზე
 */
const photos: PhotosModel = {
    languages:  [
        {languageCode:'ka', languageName: 'ქართული'},
        {languageCode:'en', languageName: 'English'}
    ],

    categories: [{   
    name: "All", 
    nameGeo: "ყველა",
    data: [
        {id: "snow-like-a-canyon", name: "The Snow like a canyon", nameGeo: "თოვლი მზგავსად კანიონისა", url:"https://iili.io/HXMCvbp.md.jpg" },
        {id: "mountain-as-clouds-barrier", name: "The Mountain as clouds barrier",  nameGeo: "მთა როგორც ღრუბლების ბარიერი", url:"https://iili.io/HXMCzOl.md.jpg" },
        {id: "algae", name: "A Algae?", nameGeo: "წყალმცენარე?", url: "https://iili.io/HXMFfI9.md.jpg" },
        {id: "puppy", name: "A Puppy", nameGeo: "ლეკვი", url: "https://iili.io/HXMrEyN.jpg" },
        {id: "spider-and-yellow-flower", name: "A Spider and a yellow flower", nameGeo: "ობობა და ყვითელი ყვავილი", url: "https://iili.io/HXMrRZF.jpg" },
        {id: "cockroach1", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMruTP.jpg" },
        {id: "black-spider", name: "A black spider", nameGeo: "შავი ობობა", url: "https://iili.io/HXMro3x.jpg" },
        {id: "ragweed", name: "A ragweed", nameGeo: "ამბროზია", url: "https://iili.io/HXMrJv2.jpg" },
        {id: "moonrise", name: "Moonrise", nameGeo: "მთვარის ამოსვლა", url: "https://iili.io/HXMrHYl.md.jpg" },
        {id: "hornet", name: "A hornet", nameGeo: "ბილაინის ბზიკი", url: "https://iili.io/HXMgp4f.md.jpg" },
        {id: "flower1", name: "An orange flower", nameGeo: "ნარინჯისფერი ყვავილი", url: "https://iili.io/HXMgtQn.md.jpg" },
        {id: "view1", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMg8Lg.md.jpg" },
        {id: "flying-ladybug", name: "A flying ladybug", nameGeo: "მფრინავი ჭიამაია", url: "https://iili.io/HXMU2cl.jpg" },
        {id: "flower2", name: "Flowers", nameGeo: "ყვავილები", url: "https://iili.io/HXMSmtn.md.jpg" },
        {id: "hedgehog", name: "A hedgehog", nameGeo: "ზღარბი", url: "https://iili.io/HXMShCb.jpg" },
        {id: "dill", name: "A Dill", nameGeo: "კამა", url: "https://iili.io/HXM8a5P.jpg" },
        {id: "red-crocus", name: "A Red crocus", nameGeo: "წითელი ზაფრანა", url: "https://iili.io/HXMvWH7.md.jpg" },
        {id: "blue-convolvulus-tricolor", name: "A blue convolvulus tricolor", nameGeo: "ლურჯი დილის ვარდი", url: "https://iili.io/HXMkw4p.jpg" },
        {id: "mushrooms", name: "Mushrooms", nameGeo: "სოკოები", url: "https://iili.io/HXMk0YP.md.jpg" },
        {id: "cockroach2", name: "A cockroach 2", nameGeo: "ხოჭო 2", url: "https://iili.io/HXMkxY7.md.jpg" },
        {id: "a-spider-and-a-rose", name: "A spider and a rose", nameGeo: "ობობა და ვარდი", url: "https://iili.io/HXMwies.jpg" },
        {id: "caterpillar1", name: "Caterpillar 1", nameGeo: "მატლი 1", url: "https://iili.io/HXMeikF.md.jpg" },
        {id: "view2", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMeg1V.md.jpg" },
        {id: "flower3", name: "A flower", nameGeo: "ყვავილი", url: "https://iili.io/HXMwTs2.md.jpg" },
        {id: "view3", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMh6GI.jpg" },
        {id: "eryngium", name: "A Eryngium", nameGeo: "სეტერო ეკალი", url: "https://iili.io/HXMhw41.md.jpg" },
        {id: "onion", name: "A onion", nameGeo: "ხახვი", url: "https://iili.io/HXMho2n.md.jpg" },
        {id: "small-tettigonioidea ", name: "A small tettigonioidea ", nameGeo: "პატარა კუტკალია", url: "https://iili.io/HXMh3IR.md.jpg" },
        {id: "cockroach3", name: "A cockroach 3", nameGeo: "ხოჭო 3", url: "https://iili.io/HXMXrge.jpg" },
        {id: "view4", name: "A view 4", nameGeo: "ხედი 4", url: "https://iili.io/HXMXAf1.jpg" },
        {id: "snail", name: "A snail", nameGeo: "ლოკოკინა", url: "https://iili.io/HXMXoDQ.jpg" },
        {id: "flower4", name: "A flower 4", nameGeo: "ყვავილი 4", url: "https://iili.io/HXMWNoB.md.jpg" },
        {id: "flower5", name: "A flower 5", nameGeo: "ყვავილი 5", url: "https://iili.io/HXMWGcu.md.jpg" },
        {id: "view5", name: "A view 5", nameGeo: "ხედი 5", url: "https://iili.io/HXMWIFn.md.jpg" },
        {id: "rumex-pulcher", name: "Rumex pulcher", nameGeo: "რომელიღაც მცენარე", url: "https://iili.io/HXMVQvj.md.jpg" },
        {id: "flower6", name: "A flower 6", nameGeo: "ყვავილი 6", url: "https://iili.io/HXMVAhB.md.jpg" },
        {id: "flower7", name: "A flower 7", nameGeo: "ყვავილი 7", url: "https://iili.io/HXMVvp4.jpg" },
        {id: "white-convolvulus-tricolor", name: "A white convolvulus tricolor", nameGeo: "თეთრი დილის ვარდი", url: "https://iili.io/HXMV6G9.md.jpg" },
        {id: "flower8", name: "A flower 8", nameGeo: "ყვავილი 8", url: "https://iili.io/HXMVJe4.jpg" },
        {id: "flower9", name: "A flower 9", nameGeo: "ყვავილი 9", url: "https://iili.io/HXMVH7f.md.jpg" },
        {id: "ladybug", name: "A ladybug", nameGeo: "ჭიამაია", url: "https://iili.io/HXMMaR4.md.jpg" },
        {id: "flower10", name: "A flower 10", nameGeo: "ყვავილი 10", url: "https://iili.io/HXMVdml.jpg" },
        {id: "flower11", name: "A flower 11", nameGeo: "ყვავილი 11", url: "https://iili.io/HXMM2iF.md.jpg" },
        {id: "flower12", name: "A flower 12", nameGeo: "ყვავილი 12", url: "https://iili.io/HXMMdV1.md.jpg" },
        {id: "flower13", name: "A flower 13", nameGeo: "ყვავილი 13", url: "https://iili.io/HXMGyNV.jpg" },
        {id: "flower14", name: "A flower 14", nameGeo: "ყვავილი 14", url: "https://iili.io/HXMG4N2.md.jpg" },
        {id: "flower15", name: "A flower 15", nameGeo: "ყვავილი 15", url: "https://iili.io/HXMGNnt.md.jpg" },
        {id: "flower16", name: "A flower 16", nameGeo: "ყვავილი 16", url: "https://iili.io/HXMGlMF.md.jpg" },
        {id: "flower17", name: "A flower 17", nameGeo: "ყვავილი 17", url: "https://iili.io/HXMG5uV.md.jpg" },
        {id: "flower18", name: "A flower 18", nameGeo: "ყვავილი 18", url: "https://iili.io/HXMEs3J.md.jpg" },
        {id: "clover", name: "Clover", nameGeo: "სამყურა", url: "https://iili.io/HXMESTB.jpg" },
        {id: "flower19", name: "A flower 19", nameGeo: "ყვავილი 19", url: "https://iili.io/HXMEO2j.md.jpg" },
        {id: "flower20", name: "A flower 20", nameGeo: "ყვავილი 20", url: "https://iili.io/HXMEMIS.md.jpg" },
        {id: "icy-grass", name: "Icy grass", nameGeo: "გაყინული ბალახი", url: "https://iili.io/HXM1P5l.md.jpg" },
        {id: "leek", name: "A leek", nameGeo: "პრასი", url: "https://iili.io/HXMaBQs.md.jpg" },
        {id: "flower21", name: "A flower 21", nameGeo: "ყვავილი 21", url: "https://iili.io/HXMaqjn.md.jpg" },
        {id: "flower22", name: "A flower 22", nameGeo: "ყვავილი 22", url: "https://iili.io/HXMafTX.md.jpg" },
        {id: "flower23", name: "A flower 23", nameGeo: "ყვავილი 23", url: "https://iili.io/HXMAJn4.jpg" },
        {id: "flower24", name: "A flower 24", nameGeo: "ყვავილი 24", url: "https://iili.io/HXMuGa9.md.jpg" },
        {id: "flower25", name: "A flower 25", nameGeo: "ყვავილი 25", url: "https://iili.io/HXMTPr7.md.jpg" },
        {id: "flower26", name: "A flower 26", nameGeo: "ყვავილი 26", url: "https://iili.io/HXMTCg9.md.jpg" },
        {id: "green-mantis", name: "A green mantis", nameGeo: "მწვანე ჩოქელა", url: "https://iili.io/HXMCmL7.md.jpg" },
        {id: "view6", name: "A view 6", nameGeo: "ხედი 6", url: "https://iili.io/HXMCDI2.md.jpg" },
        {id: "fire", name: "Fire", nameGeo: "ცეცხლი", url: "https://iili.io/HXMC1OQ.md.jpg" },
        {id: "oak", name: "An oak", nameGeo: "მუხა", url: "https://iili.io/HXMCBls.md.jpg" },
        {id: "river", name: "A river", nameGeo: "მდინარე", url: "https://iili.io/HXMBmla.md.jpg" },
        {id: "view7", name: "A view 7", nameGeo: "ხედი 7", url: "https://iili.io/HXMBiNV.md.jpg" },
        {id: "leafs-of-oak", name: "leafs of oak", nameGeo: "მუხის ფოთლები", url: "https://iili.io/HXMBGPn.md.jpg" },
        {id: "bird", name: "A bird", nameGeo: "ჩიტი", url: "https://iili.io/HXMqiCX.jpg" },
        {id: "caterpillar2", name: "Caterpillar 2", nameGeo: "მატლი 2", url: "https://iili.io/HXMqhhP.md.jpg" },
        {id: "mouse", name: "A mouse", nameGeo: "თაგვი", url: "https://iili.io/HXMq7h7.md.jpg" },
        {id: "gray-mantis", name: "A gray mantis", nameGeo: "ნაცრისფერი ჩოქელა", url: "https://iili.io/HXMqxrG.md.jpg" },
        {id: "view8", name: "A view 8", nameGeo: "ხედი 8", url: "https://iili.io/HXMqddv.md.jpg" },
        {id: "puppy-and-cat", name: "A puppy and a cat", nameGeo: "ლეკვი და კატა", url: "https://iili.io/HXXFzHx.md.jpg" } 
    ]
},
{
    name : "Flowers", 
    nameGeo : "ყვავილები",
    data : [
{id: 'spider-and-yellow-flower', name: 'A Spider and a yellow flower', nameGeo: 'ობობა და ყვითელი ყვავილი', url: 'https://iili.io/HXMrRZF.jpg'},
{id: 'flower1', name: 'An orange flower', nameGeo: 'ნარინჯისფერი ყვავილი', url: 'https://iili.io/HXMgtQn.md.jpg'},
{id: 'flower2', name: 'Flowers', nameGeo: 'ყვავილები', url: 'https://iili.io/HXMSmtn.md.jpg'},
{id: 'red-crocus', name: 'A Red crocus', nameGeo: 'წითელი ზაფრანა', url: 'https://iili.io/HXMvWH7.md.jpg'},
{id: 'blue-convolvulus-tricolor', name: 'A blue convolvulus tricolor', nameGeo: 'ლურჯი დილის ვარდი', url: 'https://iili.io/HXMkw4p.jpg'},
{id: 'a-spider-and-a-rose', name: 'A spider and a rose', nameGeo: 'ობობა და ვარდი', url: 'https://iili.io/HXMwies.jpg'} ,
{id: 'flower3', name: 'A flower', nameGeo: 'ყვავილი', url: 'https://iili.io/HXMwTs2.md.jpg'},
{id: 'flower4', name: 'A flower 4', nameGeo: 'ყვავილი 4', url: 'https://iili.io/HXMWNoB.md.jpg'},
{id: 'flower5', name: 'A flower 5', nameGeo: 'ყვავილი 5', url: 'https://iili.io/HXMWGcu.md.jpg'},
{id: 'flower6', name: 'A flower 6', nameGeo: 'ყვავილი 6', url: 'https://iili.io/HXMVAhB.md.jpg'},
{id: 'flower7', name: 'A flower 7', nameGeo: 'ყვავილი 7', url: 'https://iili.io/HXMVvp4.jpg'},
{id: 'white-convolvulus-tricolor', name: 'A white convolvulus tricolor', nameGeo: 'თეთრი დილის ვარდი', url: 'https://iili.io/HXMV6G9.md.jpg'},
{id: 'flower8', name: 'A flower 8', nameGeo: 'ყვავილი 8', url: 'https://iili.io/HXMVJe4.jpg'},
{id: 'flower9', name: 'A flower 9', nameGeo: 'ყვავილი 9', url: 'https://iili.io/HXMVH7f.md.jpg'}, 
{id: 'flower10', name: 'A flower 10', nameGeo: 'ყვავილი 10', url: 'https://iili.io/HXMVdml.jpg'},
{id: 'flower11', name: 'A flower 11', nameGeo: 'ყვავილი 11', url: 'https://iili.io/HXMM2iF.md.jpg'},
{id: 'flower12', name: 'A flower 12', nameGeo: 'ყვავილი 12', url: 'https://iili.io/HXMMdV1.md.jpg'},
{id: 'flower13', name: 'A flower 13', nameGeo: 'ყვავილი 13', url: 'https://iili.io/HXMGyNV.jpg'},
{id: 'flower14', name: 'A flower 14', nameGeo: 'ყვავილი 14', url: 'https://iili.io/HXMG4N2.md.jpg'},
{id: 'flower15', name: 'A flower 15', nameGeo: 'ყვავილი 15', url: 'https://iili.io/HXMGNnt.md.jpg'},
{id: 'flower16', name: 'A flower 16', nameGeo: 'ყვავილი 16', url: 'https://iili.io/HXMGlMF.md.jpg'},
{id: 'flower17', name: 'A flower 17', nameGeo: 'ყვავილი 17', url: 'https://iili.io/HXMG5uV.md.jpg'},
{id: 'flower18', name: 'A flower 18', nameGeo: 'ყვავილი 18', url: 'https://iili.io/HXMEs3J.md.jpg'},
{id: 'flower19', name: 'A flower 19', nameGeo: 'ყვავილი 19', url: 'https://iili.io/HXMEO2j.md.jpg'},
{id: 'flower20', name: 'A flower 20', nameGeo: 'ყვავილი 20', url: 'https://iili.io/HXMEMIS.md.jpg'},
{id: 'flower21', name: 'A flower 21', nameGeo: 'ყვავილი 21', url: 'https://iili.io/HXMaqjn.md.jpg'},
{id: 'flower22', name: 'A flower 22', nameGeo: 'ყვავილი 22', url: 'https://iili.io/HXMafTX.md.jpg'},
{id: 'flower23', name: 'A flower 23', nameGeo: 'ყვავილი 23', url: 'https://iili.io/HXMAJn4.jpg'},
{id: 'flower24', name: 'A flower 24', nameGeo: 'ყვავილი 24', url: 'https://iili.io/HXMuGa9.md.jpg'},
{id: 'flower25', name: 'A flower 25', nameGeo: 'ყვავილი 25', url: 'https://iili.io/HXMTPr7.md.jpg'},
{id: 'flower26', name: 'A flower 26', nameGeo: 'ყვავილი 26', url: 'https://iili.io/HXMTCg9.md.jpg'}
    ]
},
{
    name: "Other",
    nameGeo: "სხვა",
    data: [
        { id: "snow-like-a-canyon", name: "The Snow like a canyon", nameGeo: "თოვლი მზგავსად კანიონისა", url: "https://iili.io/HXMCvbp.md.jpg" },
        { id: "algae", name: "A Algae?", nameGeo: "წყალმცენარე?", url: "https://iili.io/HXMFfI9.md.jpg" },
        { id: "ragweed", name: "A ragweed", nameGeo: "ამბროზია", url: "https://iili.io/HXMrJv2.jpg" },
        { id: "dill", name: "A Dill", nameGeo: "კამა", url: "https://iili.io/HXM8a5P.jpg" },
        { id: "mushrooms", name: "Mushrooms", nameGeo: "სოკოები", url: "https://iili.io/HXMk0YP.md.jpg" },
        { id: "eryngium", name: "A Eryngium", nameGeo: "სეტერო ეკალი", url: "https://iili.io/HXMhw41.md.jpg" },
        { id: "onion", name: "A onion", nameGeo: "ხახვი", url: "https://iili.io/HXMho2n.md.jpg" },
        { id: "rumex-pulcher", name: "Rumex pulcher", nameGeo: "რომელიღაც მცენარე", url: "https://iili.io/HXMVQvj.md.jpg" },
        { id: "clover", name: "Clover", nameGeo: "სამყურა", url: "https://iili.io/HXMESTB.jpg" },
        { id: "icy-grass", name: "Icy grass", nameGeo: "გაყინული ბალახი", url: "https://iili.io/HXM1P5l.md.jpg" },
        { id: "leek", name: "A leek", nameGeo: "პრასი", url: "https://iili.io/HXMaBQs.md.jpg" },
        { id: "fire", name: "Fire", nameGeo: "ცეცხლი", url: "https://iili.io/HXMC1OQ.md.jpg" },
        { id: "oak", name: "An oak", nameGeo: "მუხა", url: "https://iili.io/HXMCBls.md.jpg" },
        { id: "leafs-of-oak", name: "leafs of oak", nameGeo: "მუხის ფოთლები", url: "https://iili.io/HXMBGPn.md.jpg" }
    ]
},
{
    name : "The Kingdom Animalia",
    nameGeo : "ცხოველთა სამეფო",
    data : [
        { id: "puppy", name: "A Puppy", nameGeo: "ლეკვი", url: "https://iili.io/HXMrEyN.jpg" },
        { id: "spider-and-yellow-flower", name: "A Spider and a yellow flower", nameGeo: "ობობა და ყვითელი ყვავილი", url: "https://iili.io/HXMrRZF.jpg" },
        { id: "cockroach1", name: "A cockroach", nameGeo: "ხოჭო", url: "https://iili.io/HXMruTP.jpg" },
        { id: "black-spider", name: "A black spider", nameGeo: "შავი ობობა", url: "https://iili.io/HXMro3x.jpg" },
        { id: "hornet", name: "A hornet", nameGeo: "ბილაინის ბზიკი", url: "https://iili.io/HXMgp4f.md.jpg" },
        { id: "flying-ladybug", name: "A flying ladybug", nameGeo: "მფრინავი ჭიამაია", url: "https://iili.io/HXMU2cl.jpg" },
        { id: "hedgehog", name: "A hedgehog", nameGeo: "ზღარბი", url: "https://iili.io/HXMShCb.jpg" },
        { id: "cockroach2", name: "A cockroach 2", nameGeo: "ხოჭო 2", url: "https://iili.io/HXMkxY7.md.jpg" },
        { id: "a-spider-and-a-rose", name: "A spider and a rose", nameGeo: "ობობა და ვარდი", url: "https://iili.io/HXMwies.jpg" },
        { id: "caterpillar1", name: "Caterpillar 1", nameGeo: "მატლი 1", url: "https://iili.io/HXMeikF.md.jpg" },
        { id: "small-tettigonioidea", name: "A small tettigonioidea", nameGeo: "პატარა კუტკალია", url: "https://iili.io/HXMh3IR.md.jpg" },
        { id: "cockroach3", name: "A cockroach 3", nameGeo: "ხოჭო 3", url: "https://iili.io/HXMXrge.jpg" },
        { id: "snail", name: "A snail", nameGeo: "ლოკოკინა", url: "https://iili.io/HXMXoDQ.jpg" },
        { id: "ladybug", name: "A ladybug", nameGeo: "ჭიამაია", url: "https://iili.io/HXMMaR4.md.jpg" },
        { id: "green-mantis", name: "A green mantis", nameGeo: "მწვანე ჩოქელა", url: "https://iili.io/HXMCmL7.md.jpg" },
        { id: "bird", name: "A bird", nameGeo: "ჩიტი", url: "https://iili.io/HXMqiCX.jpg" },
        { id: "caterpillar2", name: "Caterpillar 2", nameGeo: "მატლი 2", url: "https://iili.io/HXMqhhP.md.jpg" },
        { id: "mouse", name: "A mouse", nameGeo: "თაგვი", url: "https://iili.io/HXMq7h7.md.jpg" },
        { id: "gray-mantis", name: "A gray mantis", nameGeo: "ნაცრისფერი ჩოქელა", url: "https://iili.io/HXMqxrG.md.jpg" },
        { id: "puppy-and-cat", name: "A puppy and a cat", nameGeo: "ლეკვი და კატა", url: "https://iili.io/HXXFzHx.md.jpg" }
    ]
},
{
    name : "Views",
    nameGeo : "ხედები",
    data: [
        { id: "mountain-as-clouds-barrier", name: "The Mountain as clouds barrier", nameGeo: "მთა როგორც ღრუბლების ბარიერი", url: "https://iili.io/HXMCzOl.md.jpg" },
        { id: "moonrise", name: "Moonrise", nameGeo: "მთვარის ამოსვლა", url: "https://iili.io/HXMrHYl.md.jpg" },
        { id: "view1", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMg8Lg.md.jpg" },
        { id: "view2", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMeg1V.md.jpg" },
        { id: "view3", name: "A view", nameGeo: "ხედი", url: "https://iili.io/HXMh6GI.jpg" },
        { id: "view4", name: "A view 4", nameGeo: "ხედი 4", url: "https://iili.io/HXMXAf1.jpg" },
        { id: "view5", name: "A view 5", nameGeo: "ხედი 5", url: "https://iili.io/HXMWIFn.md.jpg" },
        { id: "view6", name: "A view 6", nameGeo: "ხედი 6", url: "https://iili.io/HXMCDI2.md.jpg" },
        { id: "river", name: "A river", nameGeo: "მდინარე", url: "https://iili.io/HXMBmla.md.jpg" },
        { id: "view7", name: "A view 7", nameGeo: "ხედი 7", url: "https://iili.io/HXMBiNV.md.jpg" },
        { id: "view8", name: "A view 8", nameGeo: "ხედი 8", url: "https://iili.io/HXMqddv.md.jpg" }
    ]
}
]}

export default photos;
